# -*- coding: utf-8 -*-
{
    'name': 'MTG HRMS Extensions',
    'version': '12.0.1.0.0',
    'summary': """MTG HRMS Extensions""",
    'description': 'Main module of MTG HRMS Extensions',
    'category': 'MTG',
    'author': 'MTG',
    'company': 'Memphis Tours',
    'website': "https://www.memphistours.com/",
    'depends': ['base','website','hr','hr_holidays','hr_expense','history_employee'],
    'data': [
        'security/hr_security.xml',
        'security/ir.model.access.csv',
        'data/sync.xml',
        'data/leaves_calculations.xml',
        'views/hr_employee_view.xml',
        'views/res_company.xml',
        'views/hr_leave_type.xml',
        'views/remove_footer.xml',
        'views/menu.xml',
    ],
    'demo': [],
    'images': [],
    'qweb': [],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
